"""Initial migration

Revision ID: 1b561079d6f4
Revises: 
Create Date: 2025-02-03 14:10:19.558281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b561079d6f4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('department_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('department_name')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room',
    sa.Column('id', sa.String(length=5), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=1), nullable=False),
    sa.Column('max_people', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('violation',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('content', sa.String(length=100), nullable=False),
    sa.Column('form', sa.String(length=30), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('account',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('classroom',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('classroom_name', sa.String(length=50), nullable=False),
    sa.Column('academic_year', sa.String(length=9), nullable=False),
    sa.Column('department_id', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('equipment_name', sa.String(length=50), nullable=True),
    sa.Column('equipment_type', sa.Integer(), nullable=True),
    sa.Column('equipment_status', sa.Integer(), nullable=True),
    sa.Column('room_id', sa.String(length=5), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staff',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('lastname', sa.String(length=50), nullable=False),
    sa.Column('firstname', sa.String(length=50), nullable=False),
    sa.Column('gender', sa.Boolean(), nullable=False),
    sa.Column('birthdate', sa.Date(), nullable=False),
    sa.Column('address', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=10), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('is_working', sa.Boolean(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('student',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('lastname', sa.String(length=50), nullable=False),
    sa.Column('firstname', sa.String(length=50), nullable=False),
    sa.Column('gender', sa.Boolean(), nullable=False),
    sa.Column('birthdate', sa.Date(), nullable=False),
    sa.Column('address', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=10), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('is_studying', sa.Boolean(), nullable=True),
    sa.Column('classroom_id', sa.String(length=20), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['classroom_id'], ['classroom.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('borrowing_list',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('borrowing_time', sa.DateTime(), nullable=False),
    sa.Column('returning_time', sa.DateTime(), nullable=False),
    sa.Column('student_id', sa.String(length=10), nullable=False),
    sa.Column('room_id', sa.String(length=5), nullable=False),
    sa.Column('staff_id', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('disposal_form',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('liquidation_date', sa.Date(), nullable=False),
    sa.Column('staff_id', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('penalty_ticket',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('staff_id', sa.String(length=10), nullable=False),
    sa.Column('student_id', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repair_ticket',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('staff_id', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detail_borrowing_list',
    sa.Column('borrow_list_id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.String(length=10), nullable=False),
    sa.Column('actual_returning_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['borrow_list_id'], ['borrowing_list.id'], ),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.PrimaryKeyConstraint('borrow_list_id', 'equipment_id')
    )
    op.create_table('detail_disposal_form',
    sa.Column('disposal_form_id', sa.String(length=10), nullable=False),
    sa.Column('equipment_id', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['disposal_form_id'], ['disposal_form.id'], ),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.PrimaryKeyConstraint('disposal_form_id', 'equipment_id')
    )
    op.create_table('detail_repair_ticket',
    sa.Column('repair_ticket_id', sa.String(length=10), nullable=False),
    sa.Column('equipment_id', sa.String(length=10), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['repair_ticket_id'], ['repair_ticket.id'], ),
    sa.PrimaryKeyConstraint('repair_ticket_id', 'equipment_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detail_repair_ticket')
    op.drop_table('detail_disposal_form')
    op.drop_table('detail_borrowing_list')
    op.drop_table('repair_ticket')
    op.drop_table('penalty_ticket')
    op.drop_table('disposal_form')
    op.drop_table('borrowing_list')
    op.drop_table('student')
    op.drop_table('staff')
    op.drop_table('equipment')
    op.drop_table('classroom')
    op.drop_table('account')
    op.drop_table('violation')
    op.drop_table('room')
    op.drop_table('role')
    op.drop_table('department')
    # ### end Alembic commands ###
