"""Fix incompatible id

Revision ID: ea951704a934
Revises: 1b561079d6f4
Create Date: 2025-02-03 14:47:01.671978

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ea951704a934'
down_revision = '1b561079d6f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detail_borrowing_list',
    sa.Column('borrow_list_id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.String(length=10), nullable=False),
    sa.Column('actual_returning_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['borrow_list_id'], ['borrowing_list.id'], ),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.PrimaryKeyConstraint('borrow_list_id', 'equipment_id')
    )
    op.create_table('detail_disposal_form',
    sa.Column('disposal_form_id', sa.String(length=10), nullable=False),
    sa.Column('equipment_id', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['disposal_form_id'], ['disposal_form.id'], ),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.PrimaryKeyConstraint('disposal_form_id', 'equipment_id')
    )
    op.create_table('detail_repair_ticket',
    sa.Column('repair_ticket_id', sa.String(length=10), nullable=False),
    sa.Column('equipment_id', sa.String(length=10), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['repair_ticket_id'], ['repair_ticket.id'], ),
    sa.PrimaryKeyConstraint('repair_ticket_id', 'equipment_id')
    )
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=10),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    op.drop_table('detail_repair_ticket')
    op.drop_table('detail_disposal_form')
    op.drop_table('detail_borrowing_list')
    # ### end Alembic commands ###
